### PR TITLE
improvement: Remove java 8 errorprone support

### PR DESCRIPTION
**Pull request by robert3005**
## After this PR

==COMMIT_MSG==
Remove support for running errorprone witth java 8 target compatibility
==COMMIT_MSG==

### CODE REVIEW

**Comment by carterkozak** [comment]
What prompted this?

**Comment by robert3005** [comment]
I originally wrote this code and since we have increased source compatibility across the board to 11 I don't think it's no longer necessary. Thought of this as a bit of a cleanup

**Comment by carterkozak** [comment]
oof it looks like java 9 support broke around 4.59.0 based on https://github.com/palantir/jvm-diagnostics/pull/96

**Comment by robert3005** [comment]
Looks like as of 2.11 error-prone requires java 11 https://github.com/google/error-prone/issues/2730

**Review by carterkozak — APPROVED** [review]

**Pull request merged**
