### PR TITLE
baseline-idea plugin adds compileOnly configuration to Intellij"s PRO…

### LINKED ISSUE #56: idea task doesn't handle compileOnly configuration
I had to grab this little snippet from @pwoody to get this working on an internal project

`build.gradle`:

```
idea {
    module {
        scopes.PROVIDED.plus += [ configurations.compileOnly ]
    }
}
```

What's the right way to fix this here in the baseline level vs in every project using the new compileOnly configuration?

### PR DESCRIPTION
**Pull request by uschi2000**
…VIDED scope (fixed #56)

### CODE REVIEW

**Comment by ash211** [comment]
@uschi2000 is there a good way for me to test this?  Can I change the gradle file of my other project to try this new version?  Or do a local publish and depend on that somehow?

Sorry for the naïveté.

**Comment by uschi2000** [comment]
you can: `./gradlew publishToMavenLocal`
then check for the version in ~/.m2: find ~/.m2 | grep baseline

and in your build script, add a mavenLocal repo:
buildScript {
  repositories {
    mavenLocal()
  }
}

**Comment by ash211** [comment]
Verified on my project.

Steps:
- publish this patched version locally
- update buildscript deps like:

```
diff --git a/build.gradle b/build.gradle
index d9ce42b..38823b6 100644
--- a/build.gradle
+++ b/build.gradle
@@ -2,10 +2,11 @@ buildscript {
     repositories {
         jcenter()
         maven { url 'https://plugins.gradle.org/m2/' }
+        mavenLocal()
     }

     dependencies {
-        classpath "com.palantir:gradle-baseline-java:0.2.4"
+        classpath "com.palantir:gradle-baseline-java:rfink-compileOnly-100-g07bad8ef84cd"
         classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.0.0"
     }
 }
```
- run `./gradlew idea`
- open in IntelliJ

Expected (and actual): can ctrl-click into classes from compileOnly dependencies, as well as make the project.

:+1: from me

**Comment by uschi2000** [comment]
Grand, thanks!

**Pull request merged**
