### PR TITLE
Revert gradle upgrade until we can fix the `compileRefaster` task

### PR DESCRIPTION
**Pull request by carterkozak**
Revert "Excavator: Upgrades gradle wrapper to the latest version (#804)"

This reverts commit 831e40d67482467fb75e137637d55af5ecfb3be9.

## Before this PR
```
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':module:compileRefaster'.
> no source files
```

## After this PR
==COMMIT_MSG==
Revert gradle upgrade until we can fix the `compileRefaster` task
==COMMIT_MSG==

### CODE REVIEW

**Comment by robert3005** [comment]
That change was to make compilerefaster work on newer gradle. If you’re failing it means you’re likely on gradle older than 5.4

**Comment by carterkozak** [comment]
@robert3005 WC is on 5.6.2 and produces this failure.

**Comment by ferozco** [comment]
How did you see this error given that we haven't released the changes made in #804 yet

**Comment by carterkozak** [comment]
`./gradlew publishToMavenLocal`. I test most error-prone/refaster changes on real projects before they're released for additional testing.

**Comment by ferozco** [comment]
Ok, We're planning on releasing a major rev in part because of this change so I'd prefer to spend some time trying to fix the issue rather than reverting. I'll do some investigation and echo back with my finding/a fix

**Comment by carterkozak** [comment]
Sounds good to me, thanks @ferozco!

**Pull request closed without merging**
