### PR TITLE
allow both old and new copyright styles

### PR DESCRIPTION
**Pull request by gracew**

### CODE REVIEW

**Comment by gracew** [comment]
@jmcampanini @uschi2000

**Comment by jmcampanini** [comment]
is the plan to keep both forever? or to use have both temporarily to allow for easier upgrades of our  codebase?

**Review by jmcampanini — APPROVED** [review]

**Comment by uschi2000** [comment]
hmm. I think I'd use the Baseline upgrade as a forcing function to adopt the correct/new format?

**Comment by gracew** [comment]
our legal team said it was ok to keep the old format for existing files. I'm fine with removing support for the old format once we have automatically converted everyone's copyrights to the new format, but I feel strongly that we should merge this change for the interim because currently people cannot upgrade to baseline 0.17.0 without converting all their existing files. doing this on a per-repo basis is a waste of time.

**Comment by j-baker** [comment]
Yeah maybe. Like, it's really really really easy to replace all the copyrights.

**Comment by gatesn** [comment]
Someone want to craft some `sed` and paste it here?

**Comment by gracew** [comment]
ok. I think we can automatically convert everyone's copyrights while also upgrading their baselines.

I'll close this and I'm going to release 0.17.1 off of develop so at least there is a release with consistent checkstyle + new file copyrights.

**Pull request closed without merging**
