### PR TITLE
Remove SwitchStatementDefaultCase error-prone check

### LINKED ISSUE #499: SwitchStatementDefaultCase clashes with MissingCasesInEnumSwitch
## What happened?

Removed default from switch statement per SwitchStatementDefaultCase, now receive MissingCasesInEnumSwitch instead.

## What did you want to happen?

Revert/disable SwitchStatementDefaultCase or otherwise make it smarter.

### LINKED ISSUE #541: SwitchStatementDefaultCase should not apply to integers
## What happened?

SwitchStatementDefaultCase applied to a switch statements on an integer, which is a totally reasonable use case for `default` (special case 1, 2, 3, 4, 5, then do something generic for all other values).

## What did you want to happen?

SwitchStatementDefaultCase should only apply to enums.

### LINKED ISSUE #580: SwitchStatementDefaultCase doesn't make sense when switching on strings
## What happened?

I wrote some code which seemed vaguely sensible, but errorprone complained:

```
/Users/dfox/eggtimer-bot/eggtimer-bot/src/main/java/com/palantir/eggtimer/ReceiveWebhookResource.java:26: Note: [SwitchStatementDefaultCase] Avoid using default case in switch statement.
        switch (webhook) {
        ^
    (see https://github.com/palantir/gradle-baseline#baseline-error-prone-checks)
```

```java
switch (webhook) {
    // InstallationRepositoriesEvent: Triggered when a repository is added or removed from an installation.
    case "installation_repositories.added":
        Events.InstallationRepositoriesEvent added = deserialize(payload);
        log.info("Added", added.repositoriesAdded());
        return;

    case "installation_repositories.removed":
        Events.InstallationRepositoriesEvent removed = deserialize(payload);
        log.info("Removed", removed.repositoriesRemoved());
        return;
        
    default:
        log.debug("Received webhook", SafeArg.of("webhook", webhook), SafeArg.of("payload", payload));
        return;
}
```

Similar to https://github.com/palantir/gradle-baseline/issues/541

## What did you want to happen?

The whole point of our custom `SwitchStatementDefaultCase` is to make error-prone's exhaustiveness checks on _enums_ more effective. If someone is switching on strings (or other non-enum things), I think it should be disabled.

### PR DESCRIPTION
**Pull request by pkoenig10**
Fixes #499
Fixes #541 
Fixes #580

## Before this PR
Baseline provides a `SwitchStatementDefaultCase` error-prone check.

## After this PR
Baseline does not provide a `SwitchStatementDefaultCase` error-prone check.

I added this back in https://github.com/palantir/gradle-baseline/pull/481 with a very narrow focus on enums used in APIs. However there a many valid uses of default case in switch statements outside the narrow scope of interacting with an API.

We've ended disabling this check on many of our internal repos. And for repos that haven't disabled this check, having it at `SUGGESTION` results in a noisy compiler output.

A number of other people have experience friction with this check, see the issues linked above.

The built-in error-prone switch statement checks should be sufficient for our uses.

### CODE REVIEW

**Comment by pkoenig10** [comment]
@iamdanfox @ferozco any thoughts on this?

**Comment by pkoenig10** [comment]
@iamdanfox @ferozco another gentle ping

**Comment by iamdanfox** [comment]
Ok so we're now just relying on product teams to know to avoid using `default` when they want to have exhaustiveness validated?

**Comment by pkoenig10** [comment]
Yes.

This check was only ever a `SUGGESTION`, so it was never a hard failure and relied on noticing the message in the compiler output.

**Comment by pkoenig10** [comment]
@iamdanfox any other concerns here?

**Review by iamdanfox — APPROVED** [review]

**Pull request merged**
