### PR TITLE
Add refaster rule to simplify empty optional asserts

### PR DESCRIPTION
**Pull request by carterkozak**
==COMMIT_MSG==
Add refaster rule to simplify empty optional asserts
==COMMIT_MSG==

### CODE REVIEW

**Comment by ferozco** [comment]
Could we also add some rules to handle `assertThat(foo).isEqualTo(Optional.of(bar)` -> `assertThat(foo).hasValue(bar)`

**Comment by carterkozak** [comment]
Sure, mind if that lands in a separate rule?

**Comment by iamdanfox** [comment]
I actually don't want to auto refactor that `assertThat(foo).hasValue(bar)`, because I think it doesn't actually improve the debuggability, while actually slightly reducing the readability (I didn't on first glance spot that `hasValue()` means the arg is an optional).

I know we have lots of refactoring power, just don't think that one is unambiguously net positive.

**Comment by ferozco** [comment]
👍

**Comment by ferozco** [comment]
@iamdanfox i think its a personal preference since to me removing the extra wrapping makes it clearer. Don't feel strongly enough to push for it if you disagree

**Pull request merged**
