### PR TITLE
Block clearspring stub packages of Guava

### PR DESCRIPTION
**Pull request by ash211**
Fixes https://github.com/palantir/gradle-baseline/issues/96

### CODE REVIEW

**Comment by ash211** [comment]
My main concern here is whether the other parts of this package (that aren't stubs of well-known Guava classes) are used in other places.  Can we use this checkstyle rule on specific classes, and not just packages?

**Comment by uschi2000** [comment]
there is this: http://checkstyle.sourceforge.net/config_imports.html#ImportControl

**Comment by uschi2000** [comment]
looking through https://github.com/addthis/stream-lib/tree/master/src/main/java/com/clearspring/analytics/util , it seems that none of that stuff should get imported by anyone.

**Comment by darora** [comment]
🎉

**Pull request merged**
