### PR TITLE
Add baseline docs

### PR DESCRIPTION
**Pull request by zoubeiri**
Merging in contents of https://github.com/palantir/baseline

### CODE REVIEW

**Comment by zoubeiri** [comment]
I'm open to structuring this differently

**Comment by uschi2000** [comment]
Does this mean that palantir/baseline will get removed?

**Comment by zoubeiri** [comment]
We might want to leave a readme with a link to the content's new location for a while before we remove the repo

**Comment by ash211** [comment]
@zoubeiri is this PR still active?

**Review by uschi2000 — APPROVED** [review]

**Comment by uschi2000** [comment]
Will reopen with never merge.

**Pull request closed without merging**
