### PR TITLE
Revert "[improvement] Ensure Optional#orElse argument is not method invocation"

### PR DESCRIPTION
**Pull request by ferozco**
Reverts palantir/gradle-baseline#655.

After testing the check on a few internal projects, @carterkozak and I found it to result in too many false positives to be worthwhile which is shame since I quite like the idea behind the check

### CODE REVIEW

**Comment by carterkozak** [comment]
thanks 👍

**Comment by markelliot** [comment]
What are some of the examples of false positives?

**Comment by ferozco** [comment]
You get a false positive if you pass any field from an immutable or conjure-defined object or use any empty collection helper method i.e. `Collections.emptyList()`

**Comment by gatesn** [comment]
@ferozco time to revert this?

**Pull request merged**
