### PR TITLE
Formatter preserves NLS comments in multiline string constants

### PR DESCRIPTION
**Pull request by carterkozak**
==COMMIT_MSG==
Failing test for multiline string constant with NLS comments
==COMMIT_MSG==

### CODE REVIEW

**Comment by iamdanfox** [comment]
Would it be better to check in the current borked behaviour with a comment explaining why it's bad? Then it's more convenient to iterate on when people branch off develop to tinker with the formatter?

**Comment by carterkozak** [comment]
Removing the `<setting id="org.eclipse.jdt.core.formatter.join_wrapped_lines" value="false"/>` line makes it more sane in some ways, but not great for code that already has an operator in the right place.

**Review by iamdanfox — APPROVED** [review]

**Comment by carterkozak** [comment]
:+1:

**Comment by carterkozak** [comment]
bulldozer nudge

**Pull request merged**
