### PR TITLE
Add junit5 static import checkstyle exclusions

### PR DESCRIPTION
**Pull request by dotCipher**
See the [org.junit.jupiter.api javadoc](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/package-summary.html) for references on [Assertions](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assertions.html) and [Assumptions](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assumptions.html)

### CODE REVIEW

**Comment by markelliot** [comment]
I'm tempted to push in the opposite direction of this, towards a single assertions library, and as a result roll back inclusion of truth and junit4 static imports.

**Comment by uschi2000** [comment]
For assertions: agree that I'd like to push people towards assertj. Do you non-assertion imports from junit5, @dotCipher ?

**Comment by dotCipher** [comment]
@uschi2000 I do use the [`Assumptions`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/Assumptions.html) as well, if that counts?  I am all for using one lib too, it's a good idea for sure.

Also, the [dynamic test user docs](http://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests) point to using [`DynamicTest.dynamicTest()`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/DynamicTest.html) statically, but that would definitely be a corner case here.

**Comment by iamdanfox** [comment]
Closing out as baseline 0.18.1 allows static imports in tests.

**Pull request closed without merging**
