### PR TITLE
Remove VariableDeclarationUsageDistance check

### PR DESCRIPTION
**Pull request by uschi2000**
… section

### CODE REVIEW

**Comment by uschi2000** [comment]
@derekcicerone

**Comment by derekcicerone-zz** [comment]
Does anyone actually modify the defaults in practice? Like how useful is it to have the 2 different sections?

**Comment by jmcampanini** [comment]
question: does this mean that it'll still be applied by default, but you can easily delete/restore it?

**re: 2 different states:** the original pt-gradle/pt-checkstyle plugins had strict/non-strict, and it just turned into people not using strict. it was not well received. it also feels really weird saying `baseline-strict` and `baseline-

**Comment by uschi2000** [comment]
non-strict mode is currently opt-in: you comment out the respective section from .baseline/checkstyle/checkstyle.xml .

**Comment by uschi2000** [comment]
After email discussion, removed the check entirely.

**Comment by jmcampanini** [comment]
:+1:

**Comment by jnew528** [comment]
+1

**Pull request merged**
