### PR TITLE
allow setup() and tearDown() for JMH benchmarks

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by ellisjoe** [comment]
eg: http://grepcode.com/file/repo1.maven.org/maven2/org.openjdk.jmh/jmh-core/1.10.3/org/openjdk/jmh/annotations/Setup.java?av=f

**Comment by markelliot** [comment]
It'd be better if you could scope this; have a strong desire to take the debate out of test method names.

**Comment by uschi2000** [comment]
+1

**Comment by ellisjoe** [comment]
think this needs to be an error-prone check then

**Comment by uschi2000** [comment]
can you not gate on the java file name? FooTest/FooTests vs FooBenchmarks?

**Comment by iamdanfox** [comment]
@ellisjoe looks like this PR hasn't moved in a while - do you want to pick it up again or are you OK with just using the weird annotation/naming for now?

```
@Setup
public void before() {

}
```

**Comment by iamdanfox** [comment]
Closing stale PR

**Pull request closed without merging**
