### PR TITLE
Feature/avoid hashmapint

### PR DESCRIPTION
**Pull request by davidscottcohen**
## Before this PR
new HashMap(int) is confusing

## After this PR

==COMMIT_MSG==
==COMMIT_MSG==

### CODE REVIEW

**Comment by carterkozak** [comment]
Recreated from #1771

**Review by carterkozak — APPROVED** [review]
lgtm, thanks!

**Comment by pkoenig10** [comment]
The intention of this check conflicts with `PreferCollectionConstructors`. It's a bit confusing for devs to have JDK constructors preferred in some cases and Guava static factory methods preferred in others.

**Comment by carterkozak** [comment]
> The intention of this check conflicts with PreferCollectionConstructors. It's confusing for devs to have JDK constructors preferred in some cases and Guava static factory methods preferred in others.

The `hashmap(int)` ctor itself is confusing, and it can cause serious problems when it's used expecting to insert the given number of elements when the value is used to size the hash table instead. That's why the `PreferCollectionConstructors` was implemented specifically to avoid flagging `Maps.newHashMapWithExpectedSize(int)`

**Pull request merged**
