### PR TITLE
Allow ErrorProne to qualify JavaTimeSystemDefaultTimeZone fix types

### PR DESCRIPTION
**Pull request by carterkozak**
SuggestedFixes.qualifyType will import if there's not already an
import with the same simple name, otherwise use a fully qualified
reference to avoid breaking compilation.

==COMMIT_MSG==
Allow ErrorProne to qualify JavaTimeSystemDefaultTimeZone fix types
==COMMIT_MSG==

### CODE REVIEW

**Comment by pkoenig10** [comment]
Ah thanks, I wasn't sure how to get the suggested fix I wanted here.

**Review by pkoenig10 — APPROVED** [review]

**Comment by mglazer** [comment]
Isn't this change potentially extremely dangerous if you don't actually vet every single place where this is called?

For example, this can potentially cause all persisted dates in a system to start being persisted 8 hours into the future all of a sudden with just a simple excavator change.

**Comment by carterkozak** [comment]
Qualifying the names helps us compile, the suggested change itself could change behavior and I don't agree with the choice to auto-apply it, but I don't have a strong opinion. It won't change persisted dates unless the values are used incorrectly though.

**Comment by pkoenig10** [comment]
Providing some context, this change was motivated because we had an issue where one service was serializing an `OffsetDateTime` with a non-UTC system default time zone and another service attempted to deserialize it as an `Instant`.

This definitely should not cause any behavior change, especially since you can't really guarantee what the system default time zone is. The system default time zone could be UTC, in which case this logic should be exactly equivalent.

**Comment by mglazer** [comment]
Sorry @carterkozak I should have commented on the actual PR where this was changed. I realize you just made a bug fix to that one.

I don't understand how this is not a behavioral change.

If my system timezone is UTC-8, and we change this to UTC, how is that not a functional change?

**Pull request merged**
