### PR TITLE
Bumped the default checkstyle version from 6.18 to 7.3.

### PR DESCRIPTION
**Pull request by eduardische**

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/gradle-baseline](https://github.com/palantir/gradle-baseline), @eduardische! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by uschi2000** [comment]
Did you try this checkstyle version on a largeish project? There are a couple of checkstyle behaviour changes that we should double-check, cf http://checkstyle.sourceforge.net/releasenotes.html

**Comment by ash211** [comment]
Hi @eduardische thanks for contributing to gradle-baseline!  Did you get a chance to look through Rob's link to Checkstyle behavior changes?

**Comment by uschi2000** [comment]
Going straight to 7.5.1. Thanks, @eduardische !

**Comment by uschi2000** [comment]
https://github.com/palantir/gradle-baseline/pull/128

**Pull request closed without merging**
